VERSION 0.6
FROM golang:1.18
WORKDIR /work

binary:
    COPY go.mod go.sum ./src
    RUN (cd ./src && go mod download)
    COPY . ./src
    COPY . ./original-src

    RUN (cd ./src && go mod tidy)
    RUN git diff --no-index ./src ./original-src

    RUN (cd ./src && go fmt ./...)
    RUN git diff --no-index ./src ./original-src

    RUN (cd ./src && CI_GOBIN_PREFIX=/.. go generate -x ./...)
    RUN git diff --no-index ./src ./original-src

    RUN (cd ./src go test -shuffle=on ./...)

    RUN (cd ./src && CGO_ENABLED=0 go build -o ${PWD}/../.bin/matchmaker ./cmd/matchmaker )
    SAVE ARTIFACT ./.bin/matchmaker

container-image:
    FROM scratch

    BUILD +binary

    COPY +binary/matchmaker /matchmaker

    ENTRYPOINT ["/matchmaker"]

    SAVE IMAGE matchmaker:latest